CREATE DATABASE goldenspoon;
USE goldenspoon;

CREATE TABLE tablebooking(
FULLNAME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
PHONENUMBER BIGINT NOT NULL,
DATE DATE NOT NULL,
TIME TIME NOT NULL,
NOOFGUEST INT NOT NULL,
SPECIALREQUEST VARCHAR(1000)
);
INSERT INTO tablebooking(FULLNAME,EMAIL,PHONENUMBER,DATE,TIME,NOOFGUEST,SPECIALREQUEST)
VALUES
("Lakshmi","lakshmi@gmail.com",9750523456,"2026-11-9","11:00:00",3,"nothing"),
("Thirupathi","thirupathi@gamil.com",6383939983,"2026-10-5","12:01:52",4,"I need some good view");
SELECT * FROM tablebooking;

CREATE TABLE login(
EMAIL VARCHAR(100)NOT NULL,
PASSWORD VARCHAR(8)
);
INSERT INTO login(EMAIL,PASSWORD)
VALUES
("lakshmi@gmail.com","12345"),
("thirupathi@gmail.com","987654");
SELECT * FROM login;

CREATE TABLE register(
NAME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
PASSWORD VARCHAR(8) NOT NULL,
REENTER_PASSWORD VARCHAR(8)NOT NULL
);
INSERT INTO register( NAME,EMAIL,PASSWORD,REENTER_PASSWORD)
VALUES
("LAKSHMI","lakshmi@gmail.com","12345","12345"),
( "THIRUPATHI","thirupathi@gmail.com","987654","987654");
SELECT * FROM register;

CREATE TABLE contactdetails(
FULLNAME VARCHAR(100)NOT NULL,
EMAILID VARCHAR(100)NOT NULL,
PHONENUMBER BIGINT NOT NULL,
SUBJECT TEXT,
MESSAGE TEXT
);
INSERT INTO contactdetails(FULLNAME,EMAILID,PHONENUMBER,SUBJECT,MESSAGE)
VALUES("LAKSHMI","lakshmi@gmail.com",9759987456,"enquiry","i need to order an food for my relative function");
SELECT * FROM contactdetails;
SHOW TABLES;
